In [1]:
import numpy as np

### numpy.array

In [2]:
# Two Dimension Array
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
# Three Dimension Array
b = np.array([[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]])
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [4]:
# UpCastring From int to float
a = np.array([[1, 2, 3.0], [4, 5, 6]])
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
# Changing the dimension of array from 2 dimension to 3 dimension
a = np.array([[1, 2, 3],
              [4, 5, 6]], ndmin=3)
a

array([[[1, 2, 3],
        [4, 5, 6]]])

In [6]:
# Changing the data type of array
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int16)
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [8]:
c = np.array([[1, 2, 3], [4, 5, 6]], dtype=complex)
c

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [9]:
# Changing the data type of elements: the data must be in tuple it cannot convert of list: 
# <i2 = int 16 bit
# <i4 = int 32 bit
# <i8 = int 64 bit

In [1]:
a = np.array([(1, 2, 3), (4, 5, 6)], dtype=[('a', '<i2'),('b', '<i4'),('c', '<i8')])
a

NameError: name 'np' is not defined

In [11]:
print(type(a[0][0]))
print(type(a[0][1]))
print(type(a[0][2]))

<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>


In [12]:
# Convert into the matrix

In [13]:
b = np.mat(a)
print(b)

[[(1, 2, 3) (4, 5, 6)]]


In [14]:
c = np.mat([[1, 2, 3], [4, 5, 6]])
c

matrix([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# matrix is subclass of array
issubclass(np.matrix, np.ndarray)

True

In [16]:
# array is subclass of matrix
issubclass(np.ndarray, np.matrix)

False

## numpy.asarray

### numpy.array is similar to numpy.asarray but there are less parameter or function in np.asarray compare with np.array

In [17]:
a = np.asarray([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
type(a)

numpy.ndarray

In [19]:
a = np.asarray([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [20]:
b = np.asarray(((1, 2, 3), (4, 5, 6)))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# Cheack equality operation

In [22]:
a is b

False

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [24]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [25]:
a is b

False

## numpy.asanyarray

### it is try to convert your data in the from of array, if data set available in non array format. if data set is already present in the from of array it will not convert int into the array. because the matrix is subclass of array

In [26]:
a = np.mat([[1, 2, 3], [4, 5, 6]])
a

matrix([[1, 2, 3],
        [4, 5, 6]])

In [27]:
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
c = np.asarray(b)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
d = np.asanyarray(a)
d

matrix([[1, 2, 3],
        [4, 5, 6]])

### Deep copy and Shallo copy

In [30]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# shallo Copy: changes in b is also show changes in a, refefance of variable of a is pass
b = a

In [32]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
b[0][0] = 100
b[0][1] = 200
b[0][2] = 300

In [34]:
b

array([[100, 200, 300],
       [  4,   5,   6]])

In [35]:
a

array([[100, 200, 300],
       [  4,   5,   6]])

In [36]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# deep copy: it create a seperate variable and store into it
c = a.copy() # c = np.copy(a)

In [38]:
b

array([[100, 200, 300],
       [  4,   5,   6]])

In [39]:
b[0][0] = 1000
b[0][1] = 2000
b[0][2] = 3000

In [40]:
b

array([[1000, 2000, 3000],
       [   4,    5,    6]])

In [41]:
a

array([[1, 2, 3],
       [4, 5, 6]])

### From function

In [42]:
a = np.fromfunction(lambda x, y: x == y, (3, 3), dtype=int)
a

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [43]:
b = np.fromfunction(lambda x, y : x + y, (3, 3), dtype=int)
b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [44]:
c = np.fromfunction(lambda x, y, z: x + y + z, (3, 3, 3), dtype=int)
c

array([[[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]])

In [45]:
d = np.fromfunction(lambda a, b, c, d: a + b + c + d, (3, 3, 3, 3), dtype=int)
d

array([[[[0, 1, 2],
         [1, 2, 3],
         [2, 3, 4]],

        [[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]],

        [[2, 3, 4],
         [3, 4, 5],
         [4, 5, 6]]],


       [[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]],

        [[2, 3, 4],
         [3, 4, 5],
         [4, 5, 6]],

        [[3, 4, 5],
         [4, 5, 6],
         [5, 6, 7]]],


       [[[2, 3, 4],
         [3, 4, 5],
         [4, 5, 6]],

        [[3, 4, 5],
         [4, 5, 6],
         [5, 6, 7]],

        [[4, 5, 6],
         [5, 6, 7],
         [6, 7, 8]]]])

### iterater and generater functions in numpy

In [46]:
generator = (i*i for i in range(5))
generator

<generator object <genexpr> at 0x0000024E625FA938>

In [47]:
np.fromiter(generator, int)

array([ 0,  1,  4,  9, 16])

### Converting string into numpy array

In [48]:
a = "1, 2, 3, 4, 5, 6"

In [49]:
result = np.fromstring(a, sep=",", dtype=int)
result

array([1, 2, 3, 4, 5, 6])

In [50]:
b = "420 430 440 450 460"

In [51]:
result = np.fromstring(b, sep=" ", dtype=int)
result

array([420, 430, 440, 450, 460])

####

In [52]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array(["aa", "bb", "cc", "dd", "ee"])
x3 = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
x4 = np.array([1.11, 2.22, 3.33, 4.44, 5.55])

In [53]:
result = np.core.records.fromarrays([x1, x2, x3, x4], names='a, b, c, d')
result

rec.array([(1, 'aa', 1.1, 1.11), (2, 'bb', 2.2, 2.22),
           (3, 'cc', 3.3, 3.33), (4, 'dd', 4.4, 4.44),
           (5, 'ee', 5.5, 5.55)],
          dtype=[('a', '<i4'), ('b', '<U2'), ('c', '<f8'), ('d', '<f8')])

In [54]:
result[1][0]

2

In [55]:
result[1][1]

'bb'

### arange

In [56]:
a = list(range(1, 11))
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [57]:
# this shows an error because the floting point number is not consider in python range function
# b = list(range(1, 10, 1.5))
# b

In [58]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
b = np.arange(1, 10, 1.5)
b

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

### linspace: linearly space elements (start, end, count_of_numbers)

In [60]:
a = np.linspace(1, 10, 10, dtype=int)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
b = np.linspace(1, 20, 10, dtype=int)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 20])

In [62]:
# it will not consider a end point
c = np.linspace(1, 30, 10, dtype=int, endpoint=False)
c

array([ 1,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [63]:
# print what steaps it will take
d = np.linspace(1, 30, num=10, retstep=True)
d

(array([ 1.        ,  4.22222222,  7.44444444, 10.66666667, 13.88888889,
        17.11111111, 20.33333333, 23.55555556, 26.77777778, 30.        ]),
 3.2222222222222223)

### logspace: it will space elements in logrithematic order (start, end, num_count, base=10(default))

In [64]:
a = np.logspace(1, 5, 10)
a

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [65]:
b = np.logspace(1, 5, num=5, base=2)
b

array([ 2.,  4.,  8., 16., 32.])

In [66]:
c = np.logspace(1, 5, num=5, endpoint=False)
c

array([1.00000000e+01, 6.30957344e+01, 3.98107171e+02, 2.51188643e+03,
       1.58489319e+04])

In [67]:
d = np.log(3)
d

1.0986122886681098

In [68]:
d = np.log10(3)
d

0.47712125471966244

### array creation zeros and ones and identity matrix

In [69]:
a = np.zeros(5, dtype=int)
a

array([0, 0, 0, 0, 0])

In [70]:
b = np.zeros((3, 3), dtype=int)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [71]:
c = np.zeros((3, 3, 3), dtype=int)
c

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [72]:
d = np.ones(5, dtype=int)
d

array([1, 1, 1, 1, 1])

In [73]:
e = np.ones((3, 3), dtype=int)
e

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [74]:
f = np.ones((3, 3, 3), dtype=int)
f

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [75]:
a = 5 + np.ones((3, 3), dtype=int)
a

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [76]:
b = 5 * np.ones((3, 3), dtype=int)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### Empty array: it will generate random numbers array

In [77]:
a = np.empty((3, 3), dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Problem no. 1

In [78]:
a = 5 + np.zeros((3, 4, 8))
a

array([[[5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.]]])

In [79]:
result = np.multiply(a, 2)
result

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

### Problem no.2

In [80]:
a = np.linspace(4, 8, 80)
a

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

### Problem no.3

In [81]:
a = "1 2 3 4 5 6 7 8 9 10"
a

'1 2 3 4 5 6 7 8 9 10'

In [82]:
result = np.fromstring(a, sep=" ", dtype=int)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Problem no4

In [83]:
a = np.zeros((4, 5, 2))
print("The dimension of array is ", np.ndim(a))
print("The size of array is: ", np.size(a))
print("The shape of array is: ", np.shape(a))
print("The length of array is: ", len(a))
print("The data type of array is: ", a.dtype)

The dimension of array is  3
The size of array is:  40
The shape of array is:  (4, 5, 2)
The length of array is:  4
The data type of array is:  float64


#### Problem no5

In [84]:
a = np.ones((3, 3, 3))
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [85]:
b = np.ones((3, 3, 3))
b

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [86]:
result = np.add(a, b)
result

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

### Array Reshape

In [87]:
a = np.arange(16).reshape((1, 16))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [88]:
a = np.arange(16).reshape((16, 1))
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [89]:
a = np.arange(16).reshape((4, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
# Reshape a data by 1 and -1 means rest of data set and -1 is equal to the rest of data set
a = np.arange(16).reshape((1, -1))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [91]:
# Reshape a data by 1 and -1 means rest of data set by default of -1 it take as 2 and -1 is equal to the rest of data set
a = np.arange(16).reshape((8, -1))
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [92]:
# Reshape a data by 4 and -1 means rest of data set by default of 4 and -1 is equal to the rest of data set
a = np.arange(16).reshape((4, -1))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
# Reshape a data by 4 and -1 means rest of data set by default of 4 and -1 is equal to the rest of data set
a = np.arange(16).reshape((-1, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Ascessing the digonal element of data of any array

In [95]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
np.diag(a)

array([ 0,  5, 10, 15])

In [97]:
a = np.arange(16).reshape((2, -1))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [98]:
result = np.diag(a)
result

array([0, 9])

In [99]:
result = np.diag(a, k=1)
result

array([ 1, 10])

In [100]:
result = np.diag(a, k=-1)
result

array([8])

In [101]:
a = np.arange(16).reshape((4, -1))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [102]:
result = np.diag(a, k=1)
result

array([ 1,  6, 11])

In [103]:
result = np.diag(a, k=2)
result

array([2, 7])

In [104]:
result = np.diag(a, k=-1)
result

array([ 4,  9, 14])

In [105]:
result = np.diag(a, k=-3)
result

array([12])

In [106]:
b = np.diag(np.diag(a))
b

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [107]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

### diagflat

In [108]:
# it will create a matrix of diagonal is after 1, putting this values of 1, 2, 3
result = np.diagflat([1, 2, 3], k=1)
result

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [109]:
# it will create a matrix of diagonal after 2 index, putting this values
result = np.diagflat([[1, 2], [3, 4]], k=2)
result

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [110]:
result = np.diagflat([[1, 2], [3, 4]], k=-1)
result

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### tri

In [111]:
# array of diagonal below the element and in upper size it is a zero
# here diagonal at k=0
result = np.tri(4, 4, 0, dtype=int)
result

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])

In [112]:
# here diagonal at k=1
result = np.tri(4, 4, 1, dtype=int)
result

array([[1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### tril: lower triangle of array

In [113]:
# elements are present on a diagonal 0 and remaining upper elements is zero
result = np.tril([[1, 2, 3], [4, 5, 6], [7, 8, 9]], k=0)
result

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [114]:
# elements are present on a diagonal 1 and remaining  upper elements is zero
result = np.tril([[1, 2, 3], [4, 5, 6], [7, 8, 9]], k=1)
result

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
# elements are present on a diagonal -1 and remaining upper elements is zero
result = np.tril([[1, 2, 3], [4, 5, 6], [7, 8, 9]], k=-1)
result

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

### triu : upper triangle of array

In [116]:
# elements are present on a diagonal 0 and remaining lower elements is zero
result = np.triu([[1, 2, 3], [4, 5, 6], [7, 8, 9]], k=0)
result

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [117]:
# elements are present on a diagonal -1 and remaining lower elements is zero
result = np.triu([[1, 2, 3], [4, 5, 6], [7, 8, 9]], k=-1)
result

array([[1, 2, 3],
       [4, 5, 6],
       [0, 8, 9]])

### Ascessing array with the help of for loop

In [118]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [119]:
for i in a:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [120]:
for i in a:
    for j in i:
        print(j, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

## Random Number Generation

### 1) .rand(m, n) : numbers lie in between of 1 to 0, uniform distrubution

### Numbers that can be lie in between of 0 to 1 is a uniform distrubution

In [121]:
print("Numbers in uniform distrubution")
print("The numbers is rangeing from 0 to 1")
num = np.random.rand(3, 3)
num

Numbers in uniform distrubution
The numbers is rangeing from 0 to 1


array([[3.08616547e-01, 4.61655861e-01, 4.84290784e-03],
       [3.63866978e-01, 8.88055999e-01, 9.90893334e-01],
       [1.67093521e-01, 1.27870597e-01, 5.32043284e-04]])

In [122]:
num = np.random.rand(3, 3)
result = 100 * num
arr = np.array(result, dtype=int)
arr

array([[40, 97, 14],
       [50, 30, 53],
       [33,  1, 21]])

### 2) .randn(m, n) : number lie in between of 1 to 0 including negative numbers, normal distrubution

### Numbers that are 0 is mean and 1 is standard noraml distrubution this numbers is standard distrubution 

In [123]:
print("Numbers in noraml distrubution")
print("the 0 is mean and is standard deviation as 1, ie. standard normal")
num = np.random.randn(3, 3)
num

Numbers in noraml distrubution
the 0 is mean and is standard deviation as 1, ie. standard normal


array([[-0.43721841, -0.05155462, -1.15320341],
       [-1.02722483,  0.79014399,  1.80539244],
       [-0.11651767, -0.15302156,  1.81190847]])

In [124]:
num = np.random.rand(3, 3)
result = num * 100
arr = np.array(result, dtype=int)
arr

array([[64, 44,  9],
       [71, 39, 77],
       [93, 46, 24]])

## 3) .randint(a, b): numbers lie in between of a to b with integers

In [125]:
print("Generate random number in range of 1 to 10")
num = np.random.randint(1, 10)
num

Generate random number in range of 1 to 10


7

In [126]:
print("Genreateing random numbers in between of 1 to 100 of 30 numbers")
num = np.random.randint(1, 100, 30)
num

Genreateing random numbers in between of 1 to 100 of 30 numbers


array([15, 66, 25, 22, 79, 27,  3, 36, 83, 59, 84, 88, 56, 18,  7, 33, 34,
       67, 65, 76, 83, 61, 56, 51, 43, 68, 80, 34, 93, 87])

In [127]:
num = np.random.randint(100, 200, (3, 3), dtype=int)
num

array([[198, 160, 161],
       [154, 187, 178],
       [124, 182, 123]])

## Reshape

In [128]:
a = np.random.randint(10, 20, 16)
result = a.reshape((4, 4))
result

array([[18, 15, 18, 16],
       [10, 18, 11, 11],
       [18, 10, 11, 12],
       [18, 18, 16, 13]])

### Sorting generated data

In [129]:
a = np.random.randint(1, 20, 16)
arr = np.sort(a)
result = arr.reshape(4, 4)
result

array([[ 1,  5,  5,  6],
       [ 6,  7,  8,  8],
       [10, 11, 13, 14],
       [16, 17, 17, 18]])

In [130]:
# Sorting the element in rowwise
b = np.random.randint(1, 50, 25).reshape((5, 5))
arr = np.sort(b, axis=1, kind='quicksort')
arr

array([[ 2,  7, 19, 38, 43],
       [10, 27, 28, 32, 44],
       [ 2, 29, 29, 32, 40],
       [15, 27, 43, 45, 46],
       [ 1,  1,  2, 34, 42]])

In [131]:
# Sorting the element in columnwise
c = np.random.randint(1, 50, 25).reshape((5, 5))
arr = np.sort(c, axis=0, kind='heapsort')
arr

array([[23,  6,  1, 12,  2],
       [32, 16,  1, 23, 13],
       [36, 21, 13, 31, 21],
       [36, 24, 24, 45, 34],
       [38, 48, 30, 49, 45]])

### 1) Maximum and Minimum element and their location

### array index start from 0

In [132]:
print("Maximum element in a is:", a.max())
print("Maximum element in b is:", b.max(axis=0))
print("Maximum element in c is:", c.max(axis=1))

Maximum element in a is: 18
Maximum element in b is: [44 45 43 32 46]
Maximum element in c is: [31 48 45 49 34]


In [133]:
# maximum element in arrays location
print("Maximum element location in a is:", a.argmax())
# here arg max function return row index of that value 
print("Maximum element location in b is:", b.argmax(axis=0))
# here arg max functiion return column index of that value
print("Maximum element location in c is:", c.argmax(axis=1))

Maximum element location in a is: 4
Maximum element location in b is: [1 3 3 1 3]
Maximum element location in c is: [3 1 4 3 4]


In [134]:
print("Minimum element in a is:", a.min())
print("Minimum element in b is:", b.min(axis=0))
print("Minimum element in c is:", c.min(axis=1))

Minimum element in a is: 1
Minimum element in b is: [27  1  7  1  2]
Minimum element in c is: [ 2  1  6 13  1]


In [135]:
# minimum element location in array 
print("Minimum element location in a is:", a.argmin())
# here arg min function return row index of that value
print("Minimum element location in b is:", b.argmin(axis=0))
# here arg min functiion return column index of that value
print("Minimum element location in c is:", c.argmax(axis=1))

Minimum element location in a is: 15
Minimum element location in b is: [3 4 0 4 4]
Minimum element location in c is: [3 1 4 3 4]


## Slicing and reshapeing array

In [136]:
arr = np.random.randint(1, 20, 10)
arr

array([18, 12,  4, 13, 11,  2,  4, 11,  8, 19])

In [137]:
print("7th element in list is:", arr[7])

7th element in list is: 11


In [138]:
print("7th to 10th element in list is:", arr[7:10])

7th to 10th element in list is: [11  8 19]


In [139]:
print("Printing the element in negative slicing:", arr[-1:-5:-1])

Printing the element in negative slicing: [19  8 11  4]


In [140]:
a = np.random.randint(1, 50, 25).reshape(5, 5)
a

array([[ 9, 42, 49, 37, 41],
       [25, 44,  1, 37, 38],
       [12,  8, 47, 26, 23],
       [19, 38, 38, 40,  7],
       [26, 32, 42, 35,  7]])

In [141]:
# all the columns of zeroth row
print("Ascessing the zeroth row: ", a[0, :])

Ascessing the zeroth row:  [ 9 42 49 37 41]


In [142]:
# all the rows of zeroth column
print("Ascessing the zeroth column: ", a[:, 0])

Ascessing the zeroth column:  [ 9 25 12 19 26]


In [143]:
arr = a[2, 1:]
arr

array([ 8, 47, 26, 23])

In [144]:
arr = a[2, :]
arr

array([12,  8, 47, 26, 23])

In [145]:
print("Printint all rows of 0th column :",a[:, 0])

Printint all rows of 0th column : [ 9 25 12 19 26]


In [146]:
print("Printing all colums of 0th row :", a[0, :])

Printing all colums of 0th row : [ 9 42 49 37 41]


In [147]:
b = np.array(np.random.randint(1, 50, 75)).reshape(3, 5, 5)
b

array([[[49, 45, 32, 16, 45],
        [12,  6,  8, 28, 24],
        [12, 49,  8, 29, 27],
        [25,  2, 39, 45, 18],
        [ 3, 46, 21, 16, 11]],

       [[42, 22, 17, 35,  2],
        [45, 33,  8, 22, 40],
        [13, 13, 20,  6, 17],
        [43, 29,  4, 22, 28],
        [41, 39, 26, 32, 34]],

       [[43,  8, 48, 35, 32],
        [22,  1,  2, 27, 13],
        [17, 16,  7, 43, 18],
        [40, 21, 41, 44, 25],
        [18,  1, 42, 11, 35]]])

In [148]:
b[1, 2, 3]

6

In [149]:
b[1, 4, :]

array([41, 39, 26, 32, 34])

In [150]:
b[0, :, 1]

array([45,  6, 49,  2, 46])

In [151]:
b[:, 0:2, :]

array([[[49, 45, 32, 16, 45],
        [12,  6,  8, 28, 24]],

       [[42, 22, 17, 35,  2],
        [45, 33,  8, 22, 40]],

       [[43,  8, 48, 35, 32],
        [22,  1,  2, 27, 13]]])

### Condition 

In [152]:
a = np.random.randint(1, 50, 25).reshape(5, 5)
a

array([[40, 10, 44,  7, 32],
       [10, 17, 39, 45,  1],
       [28, 30, 38, 31,  2],
       [ 4, 27, 28,  6, 22],
       [30, 20, 10, 33, 45]])

In [153]:
print("Where the element is greater than 20")
a>10

Where the element is greater than 20


array([[ True, False,  True, False,  True],
       [False,  True,  True,  True, False],
       [ True,  True,  True,  True, False],
       [False,  True,  True, False,  True],
       [ True,  True, False,  True,  True]])

In [154]:
print("Which element is greater than 20")
a[a>10]

Which element is greater than 20


array([40, 44, 32, 17, 39, 45, 28, 30, 38, 31, 27, 28, 22, 30, 20, 33, 45])

In [155]:
arr = a[a>10]
print("The numbers which is greater than 10")
print(arr)
print("Total number of element which is greater than 10")
l = len(arr)
print(l)
print("Creating the new element of that numbers")
# result = arr.reshape((6, ))
# result

The numbers which is greater than 10
[40 44 32 17 39 45 28 30 38 31 27 28 22 30 20 33 45]
Total number of element which is greater than 10
17
Creating the new element of that numbers


### Arithematic in array

In [156]:
a = np.random.randint(1, 50, 9).reshape(3, 3)
print("First matrix: ")
print(a)
b = np.random.randint(1, 50, 9).reshape(3, 3)
print("Second matrix: ")
print(b)

First matrix: 
[[49 49 11]
 [32  1  6]
 [11 34 29]]
Second matrix: 
[[38  6 29]
 [46 14 10]
 [37  8 45]]


#### index wise or element wise multiplication

In [157]:
result = a * b
result

array([[1862,  294,  319],
       [1472,   14,   60],
       [ 407,  272, 1305]])

#### matrix multiplication

In [158]:
result = a @ b
result

array([[4523, 1068, 2406],
       [1484,  254, 1208],
       [3055,  774, 1964]])

#### Zero division

In [159]:
result = a / 0
result

c:\users\abc\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

#### addition of matrices

In [160]:
result = a + b
result

array([[87, 55, 40],
       [78, 15, 16],
       [48, 42, 74]])

#### Square of matrices

In [161]:
# result = a ** 2 
result = pow(a, 2)
result

array([[2401, 2401,  121],
       [1024,    1,   36],
       [ 121, 1156,  841]], dtype=int32)

### Array Broadcasting

In [162]:
a = np.zeros((3, 3), dtype=int)
a = a + 100
a

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [163]:
b = np.array([1, 2, 3])
result = a + b
result

array([[101, 102, 103],
       [101, 102, 103],
       [101, 102, 103]])

In [164]:
b = np.array([[1, 2, 3]]).T
b

array([[1],
       [2],
       [3]])

In [165]:
result = a + b
result

array([[101, 101, 101],
       [102, 102, 102],
       [103, 103, 103]])

### Array mathematics

In [166]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
b = np.arange(1, 10).reshape(3, 3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [168]:
square_root = np.sqrt(a)
square_root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [169]:
expontional = np.exp(a)
expontional

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [170]:
log_base_10 = np.log10(a)
log_base_10

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [171]:
module_remainder = np.fmod(a, b)
module_remainder

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [172]:
print("Combination of functions by shwoing exponetial decay of a sine wave",)
a = np.linspace(0,12*np.pi,1001)
a

Combination of functions by shwoing exponetial decay of a sine wave


array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])