## np.array()

In [1]:
import numpy as np

#### 1 dimensional array

In [2]:
array = np.array([[1, 2, 3]])
array

array([[1, 2, 3]])

In [3]:
type(array)

numpy.ndarray

#### 2 dimensional array

In [4]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
type(array)

numpy.ndarray

#### Upcasting of array: int into float

In [6]:
array = np.array([[1, 2, 3], [3.14, 4, 5], [6, 7, 8]])
array

array([[1.  , 2.  , 3.  ],
       [3.14, 4.  , 5.  ],
       [6.  , 7.  , 8.  ]])

#### Downcasting of array: float into int

In [7]:
array = np.array([[1, 2, 3], [3.14, 4, 5], [6, 7, 8]], dtype=int)
array

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

#### Data Converting

In [8]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=complex)
array

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [9]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int16)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)

#### Changing the data type of elements: the data must be in tuple it cannont convert list data, 
* 1) <i2 = int 16 bit
* 2) i<i4 = int 32 bit 
* 3) i<i8 = int 64 bit

In [10]:
array = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)], dtype=[('a', '<i2'), ('b', '<i4'), ('c', '<i8')])
array

array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
      dtype=[('a', '<i2'), ('b', '<i4'), ('c', '<i8')])

In [11]:
print(type(array[0][0]))
print(type(array[0][1]))
print(type(array[0][2]))

<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>


#### Specifying the dimension of array: 2 dimension array into 3 dimension

In [12]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], ndmin=3)
array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

#### Matrix

In [13]:
matrix = np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
matrix = np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float)
matrix

matrix([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

#### matrix is subclass of array

In [15]:
issubclass(np.matrix, np.ndarray)

True

## np.asarray(): 
* it is similar to np.array but there are more features is availabe in np.array() compare to the np.asarray(). 

In [16]:
array = np.asarray([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
array = np.asarray([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int16)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)

In [18]:
type(array)

numpy.ndarray

#### Equality cheack

In [19]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [20]:
b = np.asarray([1, 2, 3])
b

array([1, 2, 3])

In [21]:
a is b

False

In [22]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [23]:
b = np.array([1, 2, 3])
b

array([1, 2, 3])

In [24]:
a is b

False

## np.asanyarray()
* it is similar to np.array().
* there are more features in np.array() compare to np.asanyarray()
* matrix is subclass of array so we have not need to convert the matrix into the array because it is already subclass of array.
* but the np.array() and np.asarray() they will convert the matrix into the array. and this np.asanyarray() it will not convert

In [25]:
array = np.asanyarray([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
array = np.asanyarray([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int16)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)

In [27]:
matrix = np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("The data type is: ", type(matrix))
matrix

The data type is:  <class 'numpy.matrix'>


matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [28]:
a = np.array(matrix)
print("The data type is:", type(a))
a

The data type is: <class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
b = np.asarray(matrix)
print("The data type is:", type(b))
b

The data type is: <class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
c = np.asanyarray(matrix)
print("The data type is:", type(c))
c

The data type is: <class 'numpy.matrix'>


matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Deep copy and Shallo copy
* in shallo copy both variables is pointing to the same variable, example if we perform changes in a then it also shows in b.
* in deep copy both variable is pointing to the different variables, example if we perform changes in a then it not reflect in b.

#### shallo copy

In [31]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [33]:
a = b

In [34]:
a[0][0] = 100
a[1][0] = 200
a[2][0] = 300

In [35]:
a

array([[100,   8,   7],
       [200,   5,   4],
       [300,   2,   1]])

In [36]:
b

array([[100,   8,   7],
       [200,   5,   4],
       [300,   2,   1]])

#### deep copy

In [37]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [39]:
result = a.copy()
result

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
result[0][0] = 100
result[1][0] = 200
result[2][0] = 300

In [41]:
result

array([[100,   2,   3],
       [200,   5,   6],
       [300,   8,   9]])

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Properties of array

In [43]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

#### 1) size

In [45]:
print("The size of array is:", a.size)

The size of array is: 9


#### 2) shape

In [46]:
print("The shape of array is:", a.shape)

The shape of array is: (3, 3)


#### 3) length

In [47]:
print("The length of array is:", len(a))

The length of array is: 3


#### 4) data type

In [48]:
print("The data type of array is:", a.dtype)

The data type of array is: int32


#### 5) dimensions

In [49]:
print("The dimension of array is:", a.ndim)

The dimension of array is: 2


## Array Mathematics

#### 1) Addition

In [50]:
result = np.add(a, b)
result

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

#### 2) Subtraction

In [51]:
result = np.subtract(a, b)
result

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

#### 3) Multiply

In [52]:
result = np.multiply(a, b)
result

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

#### 4) Division

In [53]:
result = np.divide(a, b)
result

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

#### 5) Exponentation

In [54]:
result = np.exp(a)
result

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

#### 6) Square root

In [55]:
result = np.sqrt(a)
result

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

#### 7) Comparison

In [56]:
result = a == b
print("Equal: ", result)
result = a != b
print("Not Equal:", result)
result = a >= b
print("Greater than equal:", result)
result = a <= b
print("Less than equal:", result)

Equal:  [[False False False]
 [False  True False]
 [False False False]]
Not Equal: [[ True  True  True]
 [ True False  True]
 [ True  True  True]]
Greater than equal: [[False False False]
 [False  True  True]
 [ True  True  True]]
Less than equal: [[ True  True  True]
 [ True  True False]
 [False False False]]


#### Array wise comparasion

In [57]:
result = np.array_equal(a, b)
result

False

## Functions

In [58]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 1) arr.sum()

In [59]:
print("The sum of elements in array is:", a.sum())

The sum of elements in array is: 45


#### 2) arr.min and arr.max, minimum and maximum element in array

In [60]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
print("The minimum element in array is:", a.min())
print("The maximum element in array is:", a.max())

The minimum element in array is: 1
The maximum element in array is: 9


In [62]:
print("The minimum element in array in row wise is:", a.min(axis=0))
print("The minimum element in array in column wise is:", a.min(axis=1))

The minimum element in array in row wise is: [1 2 3]
The minimum element in array in column wise is: [1 4 7]


In [63]:
print("The maximum element in array in row wise is:", a.max(axis=0))
print("The maximum element in array in column wise is:", a.max(axis=1))

The maximum element in array in row wise is: [7 8 9]
The maximum element in array in column wise is: [3 6 9]


#### 3) mean

In [70]:
print("The mean of data is:", a.mean())

The mean of data is: 0.3333333333333333


#### 4) median

In [72]:
print("The median of data is:", np.median(a))

The median of data is: 0.0


#### 5) correlation coefficient

In [74]:
print("The correlation coefficient is:", np.corrcoef(a))

The correlation coefficient is: [[ 1.  -0.5 -0.5]
 [-0.5  1.  -0.5]
 [-0.5 -0.5  1. ]]


## from function

In [65]:
a = np.fromfunction(lambda x, y: x==y, (3, 3), dtype=int)
a

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [66]:
b = np.fromfunction(lambda x, y: (x+y), (3, 3), dtype=int)
b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [67]:
c = np.fromfunction(lambda x, y, z: x+y+z, (3, 3, 3), dtype=int)
c

array([[[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]])

## Operations

#### 1) Sort operation

#### 2) reshape

In [80]:
a = np.random.randint(1, 20, 12).reshape(4, 3)
a

array([[ 2,  1, 10],
       [14,  3,  4],
       [10,  4, 17],
       [15,  4,  9]])

#### 3) adding

In [81]:
a = np.random.randint(1, 20, 12).reshape(4, 3)
a

array([[14,  4, 19],
       [18,  1,  9],
       [17,  4, 16],
       [ 4, 10,  1]])

In [85]:
b = np.random.randint(100, 200, 12).reshape(4, 3)
b

array([[125, 192, 153],
       [198, 101, 137],
       [153, 186, 197],
       [185, 108, 124]])

In [87]:
result = np.append(a, b)
result

array([ 14,   4,  19,  18,   1,   9,  17,   4,  16,   4,  10,   1, 125,
       192, 153, 198, 101, 137, 153, 186, 197, 185, 108, 124])

In [88]:
print("The number of element in array is:", len(result))

The number of element in array is: 24


In [89]:
result = result.reshape(8, 3)
result

array([[ 14,   4,  19],
       [ 18,   1,   9],
       [ 17,   4,  16],
       [  4,  10,   1],
       [125, 192, 153],
       [198, 101, 137],
       [153, 186, 197],
       [185, 108, 124]])

In [93]:
result = np.insert(a, 3, [10, 20, 30, 50])
result

array([14,  4, 19, 10, 20, 30, 50, 18,  1,  9, 17,  4, 16,  4, 10,  1])

In [94]:
print("The number of element in array is:", len(result))

The number of element in array is: 16


In [95]:
result = result.reshape(4, 4)
result

array([[14,  4, 19, 10],
       [20, 30, 50, 18],
       [ 1,  9, 17,  4],
       [16,  4, 10,  1]])