In [1]:
import numpy as np

In [2]:
# 1 dimensional array
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [3]:
# 2 dimensional array
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
Sum = b.sum(axis=0)
Sum

array([5, 7, 9])

In [5]:
Sum = b.sum(axis=1)
Sum

array([ 6, 15])

### Properties of array

In [6]:
# total no of element
b.size

6

In [7]:
# Shape of array
b.shape

(2, 3)

In [8]:
# length of array
len(a)

5

In [9]:
# type of data
a.dtype

dtype('int32')

In [10]:
# no of dimension
a.ndim

1

## array mathematics

## 1) Arithmetic Operation

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
result = np.add(a, b)
result

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
result = np.subtract(a, b)
result

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
result = np.multiply(a, b)
result

array([[ 1,  4,  9],
       [16, 25, 36]])

In [16]:
result = np.divide(a, b)
result

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
result = np.exp(a)
result

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [18]:
result = np.sqrt(a)
result

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## 2) Comparasion operation

### Element wise comparasion

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
result = (a == b)
result

array([[ True,  True,  True],
       [ True,  True,  True]])

In [22]:
result = (a != b)
result

array([[False, False, False],
       [False, False, False]])

In [23]:
result = (a>b)
result

array([[False, False, False],
       [False, False, False]])

In [24]:
result = (a<b)
result

array([[False, False, False],
       [False, False, False]])

### array wise comparasion

In [25]:
result = np.array_equal(a, b)
result

True

## functions

In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# maximum element in column
result = a.max(axis=0)
result

array([4, 5, 6])

In [29]:
# minimum element in row
result = a.max(axis=1)
result

array([3, 6])

In [30]:
# minimum element in column
result = a.min(axis=0)
result

array([1, 2, 3])

In [31]:
# minimum element in row
result = a.min(axis=1)
result

array([1, 4])

In [32]:
np.mean(a)

3.5

In [33]:
np.median(a)

3.5

In [34]:
np.corrcoef(a)

array([[1., 1.],
       [1., 1.]])

In [35]:
np.std(a)

1.707825127659933

## Operations

In [36]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
b = np.arange(10, 1, -1).reshape(3, 3)
b

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

### 1) Deep copy

In [38]:
a_copy = np.copy(a)
a_copy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 2) Sorting

In [39]:
b

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

#### Sort element column wise

In [40]:
sorted_b = b.sort(axis=1)
b

array([[ 8,  9, 10],
       [ 5,  6,  7],
       [ 2,  3,  4]])

#### Sort element row wise

In [41]:
sorted_b = b.sort(axis=0)
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 3) Reshape

In [42]:
arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 4) Adding

In [43]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### append: adding to the end of the list

In [44]:
arr = np.append(a, [10, 20, 30])
result = arr.reshape(4, 3)
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30]])

#### insert: inserting value on the index

In [45]:
arr = np.insert(a, 3, [100, 200, 300])
result = arr.reshape(4, 3)
result

array([[  1,   2,   3],
       [100, 200, 300],
       [  4,   5,   6],
       [  7,   8,   9]])

### 5) Removeing

In [46]:
result

array([[  1,   2,   3],
       [100, 200, 300],
       [  4,   5,   6],
       [  7,   8,   9]])

#### deleting element with the help of indices

In [47]:
result1 = np.delete(result, [[3, 4, 5]])
new_arr = result1.reshape(3, 3)
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### deleting the third column of array

In [48]:
result2 = np.delete(result, 3, axis=0)
result2

array([[  1,   2,   3],
       [100, 200, 300],
       [  4,   5,   6]])

#### deleting the second column of array

In [49]:
result3 = np.delete(result, 2, axis=1)
result3

array([[  1,   2],
       [100, 200],
       [  4,   5],
       [  7,   8]])

### 6) Combinining

In [50]:
a = np.arange(1, 17).reshape(4, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [51]:
b = np.arange(17, 1, -1).reshape(4, 4)
b

array([[17, 16, 15, 14],
       [13, 12, 11, 10],
       [ 9,  8,  7,  6],
       [ 5,  4,  3,  2]])

#### adding 2nd array to the 1st array at the end of array

In [52]:
result1 = np.concatenate((a, b), axis=0)
result1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 16, 15, 14],
       [13, 12, 11, 10],
       [ 9,  8,  7,  6],
       [ 5,  4,  3,  2]])

#### adding 2nd array to the 1st array at the end of array

In [53]:
result2 = np.concatenate((a, b), axis=1)
result2

array([[ 1,  2,  3,  4, 17, 16, 15, 14],
       [ 5,  6,  7,  8, 13, 12, 11, 10],
       [ 9, 10, 11, 12,  9,  8,  7,  6],
       [13, 14, 15, 16,  5,  4,  3,  2]])

#### sorting the element rowwise

In [54]:
sorted_result2 = result2.sort(axis=0)
sorted_result2

In [55]:
result2

array([[ 1,  2,  3,  4,  5,  4,  3,  2],
       [ 5,  6,  7,  8,  9,  8,  7,  6],
       [ 9, 10, 11, 12, 13, 12, 11, 10],
       [13, 14, 15, 16, 17, 16, 15, 14]])

### Spliting

In [57]:
a = np.arange(0, 12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### vertically spliting array into 3 different array

In [58]:
result = np.hsplit(a, 3)
result

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]

### horizontally spliting array into 4 different array

In [60]:
result = np.vsplit(a, 4)
result

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]])]

### Stack 

In [64]:
arr1 = np.arange(1, 13).reshape(4, 3)
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
arr2 = np.arange(13, 1, -1).reshape(4, 3)
arr2

array([[13, 12, 11],
       [10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

### 1) Horizontal stack

In [66]:
result = np.stack((arr1, arr2), axis=0)
result

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 12, 11],
        [10,  9,  8],
        [ 7,  6,  5],
        [ 4,  3,  2]]])

### 2) Vertical Stack

In [67]:
result = np.stack((arr1, arr2), axis=1)
result

array([[[ 1,  2,  3],
        [13, 12, 11]],

       [[ 4,  5,  6],
        [10,  9,  8]],

       [[ 7,  8,  9],
        [ 7,  6,  5]],

       [[10, 11, 12],
        [ 4,  3,  2]]])

#### 1) np.arange(start, end, step) : it takes input as float values also, by default step size is 1

In [62]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### 2) np.count_nonzero(arr) : count total non zero numbers and return their sum

In [63]:
new_arr = np.count_nonzero(arr)
new_arr

12