In [1]:
import numpy as np

In [3]:
arr1 = np.arange(0, 20).reshape(5, 4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### 1) Normal Printing

In [4]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]


In [7]:
for i in arr1:
    for j in i:
        print(j, end=", ")

0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 

### 2) C-order

In [9]:
for x in np.nditer(arr1, order="c"):
    print(x, end=", ")

0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 

### 3) Fortran order

In [10]:
for x in np.nditer(arr1, order="F", flags=['external_loop']):
    print(x)

[ 0  4  8 12 16]
[ 1  5  9 13 17]
[ 2  6 10 14 18]
[ 3  7 11 15 19]


### 4) Square of each element in array

In [13]:
for x in np.nditer(arr1, op_flags=['readwrite']):
    x[...] = x * x

In [14]:
arr1

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

### 5) iterate through two numpy array

In [15]:
arr1 = np.arange(0, 20).reshape(5, 4)
arr2 = np.arange(20, 0, -1).reshape(5, 4)

In [16]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [17]:
arr2

array([[20, 19, 18, 17],
       [16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [19]:
for x, y in np.nditer([arr1, arr2]):
    print(x, y, end=", ")

0 20, 1 19, 2 18, 3 17, 4 16, 5 15, 6 14, 7 13, 8 12, 9 11, 10 10, 11 9, 12 8, 13 7, 14 6, 15 5, 16 4, 17 3, 18 2, 19 1, 