In [1]:
import numpy as np
import time
import sys

### numpy array

In [2]:
a = np.array([10, 20, 30, 40, 50])

In [3]:
a[0]

10

In [4]:
a[4]

50

In [5]:
a[:]

array([10, 20, 30, 40, 50])

In [6]:
a[::-1]

array([50, 40, 30, 20, 10])

### array size

In [7]:
l = range(1000)
print(sys.getsizeof(5) * len(l))

28000


In [8]:
a = np.arange(1000)
print(a.size * a.itemsize)

4000


In [9]:
SIZE = 1000000

In [10]:
a = range(SIZE)
b = range(SIZE)

In [11]:
start = time.time()

In [12]:
result = [(i*j) for i, j in zip(a, b)]

In [13]:
print("The python list:", (time.time() - start) * 1000)

The python list: 208.88638496398926


In [14]:
a = np.arange(SIZE)
b = np.arange(SIZE)

In [15]:
start = time.time()

In [16]:
result = np.add(a, b)

In [17]:
print("The numpy array:", (time.time()-start)*1000)

The numpy array: 58.33840370178223


In [23]:
a = np.array([10, 20, 30])
a

array([10, 20, 30])

In [24]:
b = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [25]:
print("The dimension of array is:", b.ndim)

The dimension of array is: 2


In [26]:
print("The item size is:", b.itemsize)

The item size is: 4


In [27]:
print("The data type is:", b.dtype)

The data type is: int32


In [28]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [29]:
print("The total no of element is:", a.size)

The total no of element is: 9


In [30]:
print("The shape of data is:", a.shape)

The shape of data is: (3, 3)


In [32]:
a = np.zeros((3, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
a = list(range(5))
a

[0, 1, 2, 3, 4]

In [42]:
a[1]

1

In [43]:
a[2]

2

In [44]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
c = np.arange(0, 10, 2)
c

array([0, 2, 4, 6, 8])

In [47]:
c = np.arange(0, 10, 3)
c

array([0, 3, 6, 9])

In [48]:
d = np.linspace(1, 100, 20)
d

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [51]:
a = np.arange(0, 12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [53]:
a.ravel()

array([10, 20, 30, 40, 50, 60, 70, 80, 90])